"""Mirror knowledge-base documents and interactive HTML assets into the temporary MkDocs source directory."""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
MARKER = ".engineering-kb-generated"
ROBOTICS_TOPIC_URL = "https://547540605.github.io/robotics-notes-site/force-control-and-compliant-assembly/"
LEGACY_ROBOTICS_REDIRECTS = {
    "index.md": "",
    "NISTIR-7901-Force-Control-Algorithms.md": "nistir-7901.html",
    "Robot-Force-Control-and-Compliant-Assembly-Learning-Path.md": "learning-path.html",
    "PI-Force-Control-Simulation.html": "PI-Force-Control-Simulation.html",
}


def main() -> None:
    if DOCS.exists():
        if not (DOCS / MARKER).exists():
            raise SystemExit(
                f"Refusing to remove unexpected directory: {DOCS}. "
                f"Delete it manually or add {MARKER} before rebuilding."
            )
        shutil.rmtree(DOCS)

    DOCS.mkdir(parents=True)
    (DOCS / MARKER).write_text(
        "Generated by scripts/sync_docs.py; do not edit or commit.\n",
        encoding="utf-8",
    )

    readme = ROOT / "README.md"
    shutil.copy2(readme, DOCS / "index.md")

    javascript_dir = DOCS / "javascripts"
    javascript_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / "scripts" / "mathjax.js", javascript_dir / "mathjax.js")

    for root_doc_name in ("CHANGELOG.md", "PLUGIN-INSTALL.md"):
        root_doc = ROOT / root_doc_name
        if root_doc.exists():
            shutil.copy2(root_doc, DOCS / root_doc.name)

    for source_dir in (ROOT / "ComputerScience", ROOT / "Engineering"):
        target_dir = DOCS / source_dir.name
        for suffix in ("*.md", "*.svg", "*.html"):
            for source_file in source_dir.rglob(suffix):
                # Preserve the privacy fix while removing LearningLab-only asset syncing.
                if "Career" in source_file.relative_to(source_dir).parts or source_file.name.lower().startswith("resume."):
                    continue
                target_file = target_dir / source_file.relative_to(source_dir)
                target_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source_file, target_file)

    # Keep published legacy URLs alive without retaining duplicate source articles.
    legacy_dir = DOCS / "Engineering" / "Robotics" / "Force-Control-and-Compliant-Assembly"
    legacy_dir.mkdir(parents=True, exist_ok=True)
    for old_name, new_path in LEGACY_ROBOTICS_REDIRECTS.items():
        url = ROBOTICS_TOPIC_URL + new_path
        redirect = (
            f'<meta http-equiv="refresh" content="0; url={url}">\n'
            f'<script>window.location.replace({url!r});</script>\n\n'
            f'[该内容已迁至机器人学专题]({url})。\n'
        )
        (legacy_dir / old_name).write_text(redirect, encoding="utf-8")


if __name__ == "__main__":
    main()
