"""Mirror knowledge-base documents and interactive HTML assets into the temporary MkDocs source directory."""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
MARKER = ".engineering-kb-generated"


def main() -> None:
    if DOCS.exists():
        if not (DOCS / MARKER).exists():
            raise SystemExit(
                f"Refusing to remove unexpected directory: {DOCS}. "
                f"Delete it manually or add {MARKER} before rebuilding."
            )
        shutil.rmtree(DOCS)

    DOCS.mkdir(parents=True)
    (DOCS / MARKER).write_text(
        "Generated by scripts/sync_docs.py; do not edit or commit.\n",
        encoding="utf-8",
    )

    readme = ROOT / "README.md"
    shutil.copy2(readme, DOCS / "index.md")

    javascript_dir = DOCS / "javascripts"
    javascript_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / "scripts" / "mathjax.js", javascript_dir / "mathjax.js")

    for root_doc_name in ("CHANGELOG.md", "PLUGIN-INSTALL.md"):
        root_doc = ROOT / root_doc_name
        if root_doc.exists():
            shutil.copy2(root_doc, DOCS / root_doc.name)

    for source_dir in (ROOT / "ComputerScience", ROOT / "Engineering"):
        target_dir = DOCS / source_dir.name
        for suffix in ("*.md", "*.svg", "*.html"):
            for source_file in source_dir.rglob(suffix):
                # Preserve the privacy fix while removing LearningLab-only asset syncing.
                if "Career" in source_file.relative_to(source_dir).parts or source_file.name.lower().startswith("resume."):
                    continue
                target_file = target_dir / source_file.relative_to(source_dir)
                target_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source_file, target_file)


if __name__ == "__main__":
    main()
