"""Mirror the knowledge-base Markdown tree into the temporary MkDocs source directory."""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
MARKER = ".engineering-kb-generated"


def main() -> None:
    if DOCS.exists():
        if not (DOCS / MARKER).exists():
            raise SystemExit(
                f"Refusing to remove unexpected directory: {DOCS}. "
                f"Delete it manually or add {MARKER} before rebuilding."
            )
        shutil.rmtree(DOCS)

    DOCS.mkdir(parents=True)
    (DOCS / MARKER).write_text(
        "Generated by scripts/sync_docs.py; do not edit or commit.\n",
        encoding="utf-8",
    )

    readme = ROOT / "README.md"
    shutil.copy2(readme, DOCS / "index.md")

    changelog = ROOT / "CHANGELOG.md"
    if changelog.exists():
        shutil.copy2(changelog, DOCS / changelog.name)

    for source_dir in (ROOT / "ComputerScience", ROOT / "Engineering"):
        target_dir = DOCS / source_dir.name
        for source_file in source_dir.rglob("*.md"):
            target_file = target_dir / source_file.relative_to(source_dir)
            target_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_file, target_file)


if __name__ == "__main__":
    main()
